using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class PointSystem : MonoBehaviour
{

    [SerializeField] public TextMeshProUGUI countdownText, endCountDownText;

    static public float currentTime;

    private void Awake()
    {
        currentTime = 300f;
    }

    // Update is called once per frame
    void Update()
    {
        currentTime -= 1 * Time.deltaTime;
        countdownText.text = "Points: " + currentTime.ToString("0");
        endCountDownText.text = currentTime.ToString("0");

        if (currentTime <= 0)
        {
            currentTime = 0;
        }
    }
}
